stages:
  - build
  - deploy
  

build-prereq:
  stage: build
  image: python:3.11.6  # Specify the Python version you want to use
  script:
    - apt-get update && apt-get install -y bash  # Install bash if not present

    

run_analysis_1:
  stage: deploy
  image: python:3.11.6  # Ensure you have the same Python version for consistency
  dependencies:
    - build-prereq  # Ensure this job runs after build-prereq
  script:
    - chmod +x run_analysis1.sh
    - ./run_analysis1.sh  # Execute the bash script

  only:
    - main  # Runs on the main branch only



run_analysis_2:
  stage: deploy
  image: python:3.11.6  # Ensure you have the same Python version for consistency
  dependencies:
    - build-prereq  # Ensure this job runs after build-prereq
  script:
    - chmod +x run_analysis2.sh
    - ./run_analysis2.sh  # Execute the bash script

  only:
    - main  # Runs on the main branch only