image: python:3.10.11  # Use the Python Docker image

test:
  stage: test
  script:
    - Get-ChildItem -Filter "testcase_*.py" | ForEach-Object {
        Write-Host "Running $_.Name..."
        python main_code.py $_.FullName
      }
