image: python:3.12  # Use Python 3.12 image

stages:
  - test

testanalysis:
  stage: test
  script:
    - echo "Running tests in true_positive_1"
    - for file in true_positive_1/testcase*.py; do python 1.py $file; done
    - echo "Running tests in true_negative_1"
    - for file in true_negative_1/testcase*.py; do python 1.py $file; done