image: python:3.10.11  # Use the Python Docker image

stages:
  - test

test:
  stage: test
  script:
    - |
      Get-ChildItem -Filter "truepositives_1/testcase*.py" | ForEach-Object {
        Write-Host "Running $($_.Name)..."
        python 1.py $_.FullName
      }