image: python:3.10.11

stages:
  - test

test_identifiers:
  stage: test
  script:
    - |
      # PowerShell syntax for looping through test cases
      Get-ChildItem -Filter "testcase_*.py" | ForEach-Object {
          Write-Host "Running $_.Name..."
          python 1.py "$($_.FullName)"
      }

rules:
  - when: on_success
  - changes:
      - testcase_*.py
