stages:
  - build
  - deploy
  

build-prereq:
  stage: build
  image: python:3.11.6  
  script:
    - apt-get update && apt-get install -y bash  

    

run_analysis_1_true_positives:
  stage: deploy
  image: python:3.11.6  
  dependencies:
    - build-prereq 
  script:
    - chmod +x run_true_positive_1.sh
    - ./run_true_positive_1.sh  

  only:
    - main  



run_analysis_1_true_negatives:
  stage: deploy
  image: python:3.11.6  
  dependencies:
    - build-prereq  
  script:
    - chmod +x run_true_negative_1.sh
    - ./run_true_negative_1.sh 

  only:
    - main  



run_analysis_2_true_positives:
  stage: deploy
  image: python:3.11.6  
  dependencies:
    - build-prereq  
  script:
    - chmod +x run_true_positive_2.sh
    - ./run_true_positive_2.sh  

  only:
    - main  



run_analysis_2_true_negatives:
  stage: deploy
  image: python:3.11.6  
  dependencies:
    - build-prereq  
  script:
    - chmod +x run_true_negative_2.sh
    - ./run_true_negative_2.sh  

  only:
    - main  



run_analysis_1_false_negative:
  stage: deploy
  image: python:3.11.6  
  dependencies:
    - build-prereq  
  script:
    - echo
    - echo
    - echo "------------------------------------------"
    - echo "Running Analysis 1 on False Negative case:"
    - python 1.py false_negative_1.py
    - echo "------------------------------------------"
    - echo
    - echo
  only:
    - main  # Runs on the main branch only


run_analysis_2_false_positive:
  stage: deploy
  image: python:3.11.6  # Ensure you have the same Python version for consistency
  dependencies:
    - build-prereq  # Ensure this job runs after build-prereq
  script:
    - echo
    - echo
    - echo "------------------------------------------"
    - echo "Running Analysis 2 on False Positive case:"
    - python 2_falsepositive.py false_positive_2.py
    - echo "------------------------------------------"
    - echo
    - echo
  only:
    - main  # Runs on the main branch only
    