image: python:3.10.11

stages:
  - test

test_identifiers:
  stage: test
  script:
    # Run all test cases in the directory
    - for file in testcase_*.py; do
        echo "Running $file...";
        python 1.py "$file";
      done